name: frontend-vite

on: 
  push: 
    branches:
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.0

      - name: instalar dependencias npm setup
        run: npm install

      - name: compilar el proyecto
        run: npm run build

      - name: Deploy To Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: eml.com.co
          username: deployeml@eml.com.co
          password: EmlPage2023
          protocol: ftp
          server-dir: ./pepitoflow.eml.com.co/
          local-dir: ./dist/